apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.service.type: LoadBalancer
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/integrating-circleci-on-noted-webapp-noted-network: "true"
        io.kompose.service: app
    spec:
      containers:
        - env:
            - name: ADMIN_EMAIL
              valueFrom:
                configMapKeyRef:
                  key: ADMIN_EMAIL
                  name: env
            - name: ADMIN_NAME
              valueFrom:
                configMapKeyRef:
                  key: ADMIN_NAME
                  name: env
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_HOST
                  name: env
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_NAME
                  name: env
            - name: DATABASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_PASSWORD
                  name: env
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_PORT
                  name: env
            - name: DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_USER
                  name: env
            - name: IP
              valueFrom:
                configMapKeyRef:
                  key: IP
                  name: env
            - name: REDIS_LOCATION
              valueFrom:
                configMapKeyRef:
                  key: REDIS_LOCATION
                  name: env
            - name: SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: SECRET_KEY
                  name: env
          image: maiempire/noted-app
          name: noted
          ports:
            - containerPort: 8000
              hostIP: 0.0.0.0
          resources: {}
          volumeMounts:
            - mountPath: /noted
              name: app-claim0
            - mountPath: /noted/frontend
              name: app-claim1
            - mountPath: /noted/media
              name: app-claim2
      restartPolicy: Always
      volumes:
        - name: app-claim0
          persistentVolumeClaim:
            claimName: app-claim0
        - name: app-claim1
          persistentVolumeClaim:
            claimName: app-claim1
        - name: app-claim2
          persistentVolumeClaim:
            claimName: app-claim2
status: {}
